
package Converter;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        AutoCompleteDecorator.decorate(b1);
        AutoCompleteDecorator.decorate(b2);
        AutoCompleteDecorator.decorate(j1);
        AutoCompleteDecorator.decorate(j2);
 }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        atas = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Temp = new javax.swing.JButton();
        Jarak = new javax.swing.JButton();
        bawah = new javax.swing.JPanel();
        temperatur = new javax.swing.JPanel();
        b1 = new javax.swing.JComboBox<>();
        b2 = new javax.swing.JComboBox<>();
        konversi1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        temp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        temp1 = new javax.swing.JTextField();
        Info1 = new javax.swing.JButton();
        jarak = new javax.swing.JPanel();
        konversi = new javax.swing.JButton();
        j1 = new javax.swing.JComboBox<>();
        j2 = new javax.swing.JComboBox<>();
        Input = new javax.swing.JTextField();
        Panah = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Info = new javax.swing.JButton();
        Output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodypanel.setBackground(new java.awt.Color(0, 0, 102));

        atas.setBackground(new java.awt.Color(51, 51, 255));

        Judul.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        Judul.setText("THIS IS CONVERTER:");

        Temp.setText("TEMPERATUR");
        Temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempActionPerformed(evt);
            }
        });

        Jarak.setText("JARAK");
        Jarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JarakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atasLayout = new javax.swing.GroupLayout(atas);
        atas.setLayout(atasLayout);
        atasLayout.setHorizontalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Temp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jarak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        atasLayout.setVerticalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Judul)
                .addGap(30, 30, 30))
            .addGroup(atasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Temp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jarak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        bawah.setLayout(new java.awt.CardLayout());

        temperatur.setBackground(new java.awt.Color(0, 153, 255));

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));

        konversi1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        konversi1.setText("KONVERSI");
        konversi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversi1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        temp.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel30.setText("→");

        temp1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        temp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp1ActionPerformed(evt);
            }
        });

        Info1.setText("INFO");
        Info1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temperaturLayout = new javax.swing.GroupLayout(temperatur);
        temperatur.setLayout(temperaturLayout);
        temperaturLayout.setHorizontalGroup(
            temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturLayout.createSequentialGroup()
                .addGroup(temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(temperaturLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(temperaturLayout.createSequentialGroup()
                                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel30)
                                .addGap(22, 22, 22)
                                .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(temperaturLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(konversi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temperaturLayout.createSequentialGroup()
                .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        temperaturLayout.setVerticalGroup(
            temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(temperaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(konversi1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bawah.add(temperatur, "card2");

        jarak.setBackground(new java.awt.Color(0, 153, 255));

        konversi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        konversi.setText("KONVERSI");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km", "Mil" }));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km", "Mil" }));

        Input.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        Panah.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Panah.setText("→");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Info.setText("INFO");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });

        Output.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jarakLayout = new javax.swing.GroupLayout(jarak);
        jarak.setLayout(jarakLayout);
        jarakLayout.setHorizontalGroup(
            jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jarakLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jarakLayout.createSequentialGroup()
                        .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Panah)
                        .addGap(22, 22, 22)
                        .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jarakLayout.createSequentialGroup()
                        .addGap(758, 758, 758)
                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jarakLayout.createSequentialGroup()
                .addGroup(jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jarakLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addGroup(jarakLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(konversi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jarakLayout.setVerticalGroup(
            jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jarakLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Panah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jarakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jarakLayout.createSequentialGroup()
                        .addComponent(konversi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addComponent(Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bawah.add(jarak, "card24");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(bawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempActionPerformed
    bawah.removeAll();
    bawah.repaint();
    bawah.revalidate();
    
    bawah.add(temperatur);
    bawah.repaint();
    bawah.revalidate();
        
    }//GEN-LAST:event_TempActionPerformed

    private void JarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JarakActionPerformed
    bawah.removeAll();
    bawah.repaint();
    bawah.revalidate();
    
    bawah.add(jarak);
    bawah.repaint();
    bawah.revalidate();
              
    
    }//GEN-LAST:event_JarakActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void konversi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversi1ActionPerformed
        // TODO add your handling code here:
 if (temp.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Mohon isi dahulu suhu yang ingin dikonversi!");
     }  
 else {    
    double suhux; 
    int suhu = Integer.parseInt(this.temp.getText());
    String besaran1=(String)b1.getSelectedItem();
    String besaran2=(String)b2.getSelectedItem();
    
    if (besaran1== "Celcius" && besaran2=="Celcius"){
        temp1.setText(temp.getText());
    }
    else if (besaran1=="Celcius" && besaran2=="Fahrenheit"){
        suhux=(9.0/5.0*suhu)+32;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Celcius" && besaran2=="Reamur"){
         suhux=(4.0/5.0*suhu);
         temp1.setText(suhux+" ");
    }      
    else if (besaran1=="Celcius" && besaran2=="Kelvin"){
         suhux=suhu+273.0;
         temp1.setText(suhux+" ");
    }
    else if (besaran1=="Fahrenheit" && besaran2=="Celcius"){
        suhux=(5.0/9.0)*(suhu-32.0);
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Fahrenheit" && besaran2=="Fahrenheit"){
        temp1.setText(temp.getText());
    }
    else if (besaran1=="Fahrenheit" && besaran2=="Reamur"){
        suhux=(4.0/9.0)*(suhu-32.0);
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Fahrenheit" && besaran2=="Kelvin"){
        suhux=(5.0/9.0)*(suhu-32.0)+273.0;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Reamur" && besaran2=="Celcius"){
        suhux=5.0/4.0*suhu;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Reamur" && besaran2=="Fahrenheit"){
        suhux=(9.0/4.0)*suhu+32.0;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Reamur" && besaran2=="Reamur"){
        temp1.setText(temp.getText());
    }
    else if (besaran1=="Reamur" && besaran2=="Kelvin"){
        suhux=(5.0/4.0*suhu)+273.0;
        temp1.setText(suhux+" ");
    }
    else if (besaran1== "Kelvin" && besaran2=="Celcius"){
        suhux=suhu-273.0;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Kelvin" && besaran2=="Fahrenheit"){
        suhux=(9.0/5.0*(suhu-273.0))+32;
        temp1.setText(suhux+" ");
    }
    else if (besaran1=="Kelvin" && besaran2=="Reamur"){
         suhux=(4.0/5.0*(suhu-273.0));
         temp1.setText(suhux+" ");
    }   
    else if (besaran1=="Kelvin" && besaran2=="Kelvin"){
         suhux=suhu+273.0;
         temp1.setText(suhux+" ");
    }
        
 }    
    }//GEN-LAST:event_konversi1ActionPerformed

    private void temp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp1ActionPerformed

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Dibuat oleh:\nHilmi Ahmad D    (21120119130048)\nM. Pratama Wibawa    (211201191300)");

    }//GEN-LAST:event_InfoActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed

        // TODO add your handling code here:
        if (Input.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon isi dahulu jarak yang ingin dikonversi!");
        }
        else {
            double jarx;
            int jar = Integer.parseInt(this.Input.getText());
            String besaran1=(String)j1.getSelectedItem();
            String besaran2=(String)j2.getSelectedItem();

            if (besaran1=="Km" && besaran2=="Mil") {
                jarx=jar*1.6;
                Output.setText(jarx+" ");
            }
            else if(besaran1=="Km" && besaran2=="Km") {
                Output.setText(Input.getText());
            }
            else if (besaran1=="Mil" && besaran2=="Km"){
                jarx=jar*1/1.6;
                Output.setText(jarx+" ");
            }
            else if (besaran1=="Mil" && besaran2=="Mil"){
                Output.setText(Input.getText());
            }
        }

    }//GEN-LAST:event_konversiActionPerformed

    private void Info1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Info;
    private javax.swing.JButton Info1;
    private javax.swing.JTextField Input;
    private javax.swing.JButton Jarak;
    private javax.swing.JLabel Judul;
    private javax.swing.JTextField Output;
    private javax.swing.JLabel Panah;
    private javax.swing.JButton Temp;
    private javax.swing.JPanel atas;
    private javax.swing.JComboBox<String> b1;
    private javax.swing.JComboBox<String> b2;
    private javax.swing.JPanel bawah;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JComboBox<String> j1;
    private javax.swing.JComboBox<String> j2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jarak;
    private javax.swing.JButton konversi;
    private javax.swing.JButton konversi1;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField temp1;
    private javax.swing.JPanel temperatur;
    // End of variables declaration//GEN-END:variables
}
